name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  npm-build:
    name: npm-build工作
    runs-on: ubuntu-latest

    steps:
    -name: 读取仓库
    uses: actions/checkout@v4

    -name: 安装依赖
    run: npm install

    -name: 构建打包
    run: npm run build



